In [1]:
import numpy as np

## Creating Numpy Arrays from Python Lists 

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
[3.14, 4, 3, 1]

[3.14, 4, 3, 1]

In [4]:
np.array([3.14, 4, 3, 1])

array([3.14, 4.  , 3.  , 1.  ])

In [5]:
np.array([1,2,3,4], dtype = 'float32')

array([1., 2., 3., 4.], dtype=float32)

In [6]:
a1 = np.array([1,2,3,4])
type(a1)

numpy.ndarray

In [7]:
a2 = np.array([[1,2,3],
               [5,6,7]])

In [8]:
type(a2)

numpy.ndarray

In [9]:
a2.shape

(2, 3)

In [10]:
a2.ndim

2

In [11]:
a2.dtype

dtype('int32')

In [12]:
#tổng số thành phần
a2.size

6

## Creating Numpy Arrays from Scratch
### `zeros`, `ones`, `full`, `arange`, `linspace`

In [13]:
np.zeros([2,4], dtype = int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [14]:
np.ones([3,5], dtype = int)

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [15]:
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [16]:
np.full([3,5], 5.2)

array([[5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2],
       [5.2, 5.2, 5.2, 5.2, 5.2]])

In [17]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### `random`

In [18]:
#seed for reproducibility
np.random.seed(0)
np.random.random([3,4])

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492]])

In [19]:
np.random.random([3,4])

array([[0.56804456, 0.92559664, 0.07103606, 0.0871293 ],
       [0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918]])

In [20]:
np.random.rand(4,4)

array([[0.11827443, 0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561, 0.77423369],
       [0.45615033, 0.56843395, 0.0187898 , 0.6176355 ],
       [0.61209572, 0.616934  , 0.94374808, 0.6818203 ]])

In [21]:
np.random.normal(0, 1, [3,4])

array([[-0.88778575, -1.98079647, -0.34791215,  0.15634897],
       [ 1.23029068,  1.20237985, -0.38732682, -0.30230275],
       [-1.04855297, -1.42001794, -1.70627019,  1.9507754 ]])

In [22]:
np.random.randint(0, 10, [3,3])

array([[4, 6, 4],
       [4, 3, 4],
       [4, 8, 4]])

## Array Indexing and Slicing

### One-dimensional subarray

In [23]:
x1 = np.random.randint(0, 20, size = 6)

In [24]:
x1

array([ 3, 15, 13, 16, 17,  5])

In [25]:
x1[4], x1[0], x1[-1]

(17, 3, 5)

### Multi-dimensional Array

In [26]:
x2 = np.random.randint(0, 20, size = [3,4])

In [27]:
x2

array([[ 9,  3,  0,  5],
       [ 0, 17, 18,  4],
       [ 2, 16,  3,  2]])

In [28]:
x2[1,2], x2[1][2]

(18, 18)

In [29]:
x2[1,2] = 6

In [30]:
x2

array([[ 9,  3,  0,  5],
       [ 0, 17,  6,  4],
       [ 2, 16,  3,  2]])

## Slicing

### `x[start:stop:step]`

In [31]:
x1

array([ 3, 15, 13, 16, 17,  5])

In [32]:
x1[0:3]

array([ 3, 15, 13])

In [33]:
x1[2:4]

array([13, 16])

In [34]:
# every other element, every 2 step
x1[::2]

array([ 3, 13, 17])

In [35]:
x2

array([[ 9,  3,  0,  5],
       [ 0, 17,  6,  4],
       [ 2, 16,  3,  2]])

In [36]:
# two rows, three columns
x2[:2,:3]

array([[ 9,  3,  0],
       [ 0, 17,  6]])

In [37]:
x2[:, :2]

array([[ 9,  3],
       [ 0, 17],
       [ 2, 16]])

## Reshaping of Arrays & Transpose

In [38]:
grid = np.arange(1,10)
grid.shape

(9,)

In [39]:
grid.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [40]:
x = np.array([1,2,3])

In [41]:
x.shape

(3,)

In [42]:
x.reshape((1,3))

array([[1, 2, 3]])

In [43]:
x.reshape((1,3)).shape

(1, 3)

In [44]:
x = np.array([[1,2],
             [3,4]])
x

array([[1, 2],
       [3, 4]])

In [45]:
x.T

array([[1, 3],
       [2, 4]])

## Array Concatenation and Splitting

In [46]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [47]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [48]:
grid = np.array([[1,2,3],[4,5,6]])
grid

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.concatenate((grid, grid)) # axis = 0

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [50]:
np.concatenate((grid, grid), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [51]:
#vstack 
x = np.array([1,2,3])
grid = np.array([[9,8,7],[6,5,4]])

In [52]:
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [53]:
#hstack

In [54]:
y = np.array([[10],[10]])

np.hstack((y,grid))

array([[10,  9,  8,  7],
       [10,  6,  5,  4]])

## Splitting of arrays

In [55]:
x = np.array([1,2,3,99,69,3,2,1])

In [56]:
x1, x2, x3 = np.split(x, [3,5])

In [57]:
x1

array([1, 2, 3])

In [58]:
x2

array([99, 69])

In [59]:
x3

array([3, 2, 1])

## Broadcasting and Vectorized operations

In [60]:
a = np.arange(3)

In [61]:
a

array([0, 1, 2])

In [62]:
a + 5 #Broadcasting

array([5, 6, 7])

In [63]:
 b = np.ones((3,3))

In [64]:
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [65]:
a.shape, b.shape

((3,), (3, 3))

In [66]:
a + b #Broadcasting

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [67]:
a * b

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [68]:
a

array([0, 1, 2])

In [69]:
c = a.reshape(3,1)

In [70]:
c

array([[0],
       [1],
       [2]])

In [71]:
a + c #Broadcasting

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

## Manipulating & Comparing Arrays

## Aggregation

In [72]:
list_number = [1,2,3]

In [73]:
ll = np.array(list_number)

In [74]:
ll

array([1, 2, 3])

In [75]:
sum(ll)  #Python sum

6

In [76]:
np.sum(ll)  #Numpy sum

6

In [77]:
# Create a massive Numpy array

massive_array = np.random.random(1000)
massive_array[:5]
massive_array.shape

(1000,)

In [78]:
%timeit sum(massive_array) #Python built-in fuction sum()
%timeit np.sum(massive_array) #Numpy

59 μs ± 929 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)
2.67 μs ± 8.9 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [79]:
np.mean(massive_array)

0.5025860508257651

In [80]:
np.min(massive_array)

5.535686500857118e-05

In [81]:
np.max(massive_array)

0.9980254861986478

In [82]:
np.std(massive_array)

0.2872430245033507

In [83]:
np.var(massive_array)

0.08250855512583254

In [84]:
 np.sqrt(np.var(massive_array))

0.2872430245033507

## Sorting arrays

### `np.sort()` uses an quicksort algorithm

In [87]:
x = np.array([2,4,3,1,5])
np.sort(x)

array([1, 2, 3, 4, 5])

### `np.argsort()` sort theo index

In [88]:
np.argsort(x)

array([3, 0, 2, 1, 4], dtype=int64)

## Sorting along rows or columns

In [90]:
np.random.seed(42)
matA = np.random.randint(0,10, size = (4,6))

In [91]:
matA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [92]:
np.sort(matA, axis = 0)

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [93]:
np.sort(matA, axis = 1)

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

## Linear Algebra

In [96]:
A = np.array([[1,2,3], [4,5,6], [7,8,9]])
B = np.array([[6,5], [4,3], [2,1]])

In [97]:
# Tích vô hướng
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [98]:
A@B

array([[20, 14],
       [56, 41],
       [92, 68]])

In [99]:
B.T @ A

array([[36, 48, 60],
       [24, 33, 42]])

## Dot product example

In [107]:
np.random.seed(0) # khi có hàng này đi các hàm random ở chương trình or máy khác cho ra kết quả giống nhau

sales_amounts = np.random.randint(20, size = (5,3))

In [103]:
sales_amounts

array([[12, 15,  0,  3,  3],
       [ 7,  9, 19, 18,  4],
       [ 6, 12,  1,  6,  7]])

In [126]:
import pandas as pd

weekly_sales = pd.DataFrame(sales_amounts, index = ["Mon", "Tue", "Wed", "Thur", "Fri"],
                            columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [127]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter
Mon              12             15              0
Tue               3              3              7
Wed               9             19             18
Thur              4              6             12
Fri               1              6              7

In [128]:
prices = np.array([10, 8, 12])

In [129]:
butter_price = pd.DataFrame(prices.reshape(1,3), index = ["Price"], columns = ["Almond Butter", "Peanut Butter", "Cashew Butter"])

In [130]:
butter_price

Almond Butter  Peanut Butter  Cashew Butter
Price             10              8             12

In [131]:
weekly_sales.shape, butter_price.T.shape

((5, 3), (3, 1))

In [132]:
weekly_sales["Total Prices"] = weekly_sales @ butter_price.T

In [133]:
weekly_sales

Almond Butter  Peanut Butter  Cashew Butter  Total Prices
Mon              12             15              0           240
Tue               3              3              7           138
Wed               9             19             18           458
Thur              4              6             12           232
Fri               1              6              7           142